server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: DETECT
org:
  hibernate:
    dialect: MySQLDialect

logging:
  pattern:
    console: d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
