server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://users-service
          predicates:
            - Path=/users/isWorking
            - Method=GET
        - id: management-status-check
          uri: lb://management-service
          predicates:
            - Path=/management/isWorking
            - Method=GET
        - id: management-users-check
          uri: lb://management-service
          predicates:
            - Path=/management/isUsersWorking
            - Method=GET
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
#http://localhost:5678/users-service/users/isWorking

eureka:
  client:
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}